-- Amaranthine dashboard tables

CREATE TABLE IF NOT EXISTS `ITEM` (
  `ITEM_NAME` VARCHAR(64) NOT NULL,
  `ITEM_LINK` VARCHAR(128) NOT NULL,
  `ITEM_COUNT` INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (`ITEM_NAME`),
  UNIQUE KEY (`ITEM_LINK`)
);

CREATE TABLE IF NOT EXISTS `FETCH` (
  `LAST_FETCH` DATETIME NOT NULL,
  PRIMARY KEY (`LAST_FETCH`)
);
